[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "#3b3b47"   # zinc   200 @accent.600
blue = "#e0e6fe"    # indigo 200 @accent.100
cyan = "#e0f4fe"    # sky    200 @accent.100
green = "#f4fee0"   # lime   200 @accent.100
magenta = "#c4b5fd" # violet 200 @accent.100
red = "#fee0e4"     # rose   200 @accent.100
white = "#eeeef0"   # zinc   200 @accent.100
yellow = "#fef8e0"  # amber  200 @accent.100

[colors.normal]
black = "#26262d"   # zinc   200 @accent.700
blue = "#8ca4fe"    # indigo 200 @accent.200
cyan = "#8cd7fe"    # sky    200 @accent.200
green = "#d7fe8c"   # lime   200 @accent.200
magenta = "#9f8cfe" # violet 200 @accent.200
red = "#fe8c9b"     # rose   200 @accent.200
white = "#c0c0ca"   # zinc   200 @accent.200
yellow = "#fee88c"  # amber  200 @accent.200

[colors.primary]
background = "0x121214"
foreground = "0xc0c0ca"

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = false
size = 12.0

[font.bold]
style = "ExtraBold"

[font.bold_italic]
style = "ExtraBold Italic"

[font.italic]
style = "Bold Italic"

[font.normal]
family = "Ioskeley Mono"
style = "Bold"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B"
key = 94

[[keyboard.bindings]]
chars = '\'
key = 93

[window]
dynamic_padding = true
opacity = 1.0
decorations = "None"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 4
y = 4
