#!/usr/bin/sh

IS_BAR_OPEN=$(eww --config "$HOME/.config/eww/sidebar/" get is_bar_panel_open)
if [ "$IS_BAR_OPEN" == "false" ]; then
    eww --config "$HOME/.config/eww/sidebar/" update is_bar_panel_open=true;
    eww --config "$HOME/.config/eww/sidebar/" open bar
else
    eww --config "$HOME/.config/eww/sidebar/" update is_bar_panel_open=false;
    eww --config "$HOME/.config/eww/sidebar/" close bar
fi
