#!/usr/bin/sh

# simple tmux sessionizer, inspired by ThePrimeagen

# dependency: find cat fzf tmux basename dirname "nerd font"

# create $HOME/.tms-entry and add path each line

TARGET=$(find $(cat $HOME/.tms-entry) -mindepth 1 -maxdepth 1 -type d | fzf --prompt "   " --pointer " ⏵" --color='pointer:4,bg+:-1,fg+:4,hl:3' --no-bold)
if [ "$TARGET" != "" ]; then
  FIRST=$(basename $(dirname $TARGET))
  SECOND=$(basename $TARGET)
  SESSION_NAME="$FIRST""_""$SECOND"
  tmux has -t $SESSION_NAME 2>/dev/null
  if [ $? != 0 ]; then
    tmux new -d -c $TARGET -s $SESSION_NAME
  fi
  if [ -z "$TMUX" ]; then
    tmux a -t $SESSION_NAME
  else
    tmux switch -t $SESSION_NAME
  fi
else
  exit 1
fi
